### ISSUE TITLE
This is not how true three-point perspective works

### ISSUE THREAD

**Issue by andersk** [Pomax/three-point-perspective#1]
As explained by many commenters on https://news.ycombinator.com/item?id=27407691, the reason your pictures came out with curved lines and distorted cubes is *not* that you did what’s “taught in art class”, and *not* that you got “too close to those vanishing points”, but rather simply that you used an incorrect exponential formula for interpolation along the perspective lines. 3D computer graphics is based on exactly the same mathematics as Renaissance perspective, not some kind of watered-down “easy-for-computer-graphics version”; it gives straight lines because lines are indeed straight, not because of a lazy approximation.

You asked me to file an issue here, so here you go.

**Comment by Pomax** [comment]
Let's calm this down: it _is_ what I was taught in art class, but it's obviously not what _you_ were taught in art class. The world is a huge place, not every school teaches the same things in the same way.

So I'm more than happy to update this post with your changes (even if it means completely rewriting this article: I don't care about internet points on a site that almost no one has heard of, I care about lasting, useful, resources on the internet) but it will be super helpful to have that information repeated here so that I can work it in. I'm perfectly happy to admit being wrong, but working on an incredible number of projects already, I wasn't joking or using hyperbole when I said I'd forget a hacker news conversation the next day: I _really_ need the information repeated in a place I can find it in the future to act on.

And thank you for taking the time to file the issue, it means a lot.

**Comment by Pomax** [comment]
A note on the actual point made in the original comment: while `1.0 - 1.0 / (1.0 + f * step)` gets us straight lines towards infinities, it also gets us an asymptotic sign change at `step=-1/f`, causing _very_ noticable render problems at the front of our scene at values for `f` that still "look like cool three point perspective", So I'll be adding some text and figures hopefully soon to show that we can mitigate the problems of exponential mapping using a rational mapping, at the cost of introducing a new, very different (but more workable) problem.

**Comment by andersk** [comment]
That corresponds to moving the camera in front of some objects in the scene, so that their light now hits you from behind; those certainly need to be culled.

**Comment by Pomax** [comment]
I've completely redone the write-up, focussing on the correct mapping, with the exponential mapping now highlighted as being the "wrong guess". Updated landed in https://github.com/Pomax/three-point-perspective/commit/2adac5a599c03b796923eda31069ff95734ef3eb
